[package]
authors = ["OKP4"]
description = "A template project for Rust."
edition = "2021"
license-file = "LICENSE"
name = "discord_bot"
readme = "README.md"
repository = "https://github.com/okp4/template-rust"
version = "0.1.0"

[dependencies]
abscissa_core = {version = "0.6.0"}
abscissa_tokio = {version = "0.6.0-pre.2", features = ["actix"]}
clap = "3"
hyper = "0.10"
serde = {version = "1", features = ["serde_derive"]}
serenity = {version = "0.11", default-features = false, features = [
  "client",
  "gateway",
  "rustls_backend",
  "model",
]}
strum = {version = "0.24", features = ["derive"]}
strum_macros = "0.24"
thiserror = "1"
tokio = {version = "1.0", features = ["time", "macros", "tracing"]}
tracing = {version = "0.1.23", features = ["log"]}

[dev-dependencies]
abscissa_core = {version = "0.6.0", features = ["testing"]}
once_cell = "1.2"
