[package]
authors = ["OKP4"]
description = "Discord bot to bridge the Dataverse!"
edition = "2021"
license-file = "LICENSE"
name = "discord_bot"
readme = "README.md"
repository = "https://github.com/okp4/discord-bot"
version = "0.1.0"

[dependencies]
abscissa_core = { version = "0.6.0" }
abscissa_tokio = { version = "0.6.0-pre.2", features = ["actix"] }
bip39 = "1"
clap = "3"
cosmos-sdk-proto = "0.13.0"
cosmrs = { git = "https://github.com/okp4/cosmos-rust", branch = "fix/addr-prefix-check" }
hyper = "0.14.20"
metrics = { version = "^0.20" }
metrics-exporter-prometheus = { version = "0.11.0", default-features = false, features = [
  "http-listener",
] }
prost = "0.10"
prost-types = "0.10"
serde = { version = "1", features = ["serde_derive"] }
serenity = { version = "0.11", default-features = false, features = [
  "client",
  "gateway",
  "rustls_backend",
  "model",
] }
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
thiserror = "1"
tokio = { version = "1.0", features = ["time", "macros", "tracing"] }
tonic = "0.7"
tracing = { version = "0.1.36", features = ["log"] }

[target.'cfg(target_os = "linux")'.dependencies]
metrics-process-promstyle = "0.18.0"

[dev-dependencies]
abscissa_core = { version = "0.6.0", features = ["testing"] }
once_cell = "1.2"

[build-dependencies]
prost-build = "0.10"
prost-wkt-build = "0.3"
tonic-build = "0.7"
